### ISSUE TITLE
Build Not Succeded 

### ISSUE THREAD

**Issue by CuriousW0lf** [localhost8083/8-Ball-Pool-Internal-Proxy-DLL-Source#1]
Using - release_x86, VS 2022

Error - 

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file '.\libs\discord-rpc.lib'	dsound	C:\Users\MONU\Downloads\Compressed\8 ball pool\8BallDLL\dsound\LINK	1

**Comment by localhost8083** [comment]
please use this lib

https://github.com/discord/discord-rpc

**Comment by wesleyadriano13** [comment]
I have the same error can anyone help?

**Comment by wesleyadriano13** [comment]
from what I understand you have to create something with discord like a discord-rpc integration for cheto the credentials and permissions, you could help me with that I would even pay for your help!

**Comment by CuriousW0lf** [comment]
> from what I understand you have to create something with discord like a discord-rpc integration for cheto the credentials and permissions, you could help me with that I would even pay for your help!

No need to pay mate, don't worry I'll give you all the libs.
Discord me Mephistopheles#7826
