### ISSUE TITLE
missing a lot of libs

### ISSUE THREAD

**Issue by a-ahmed** [localhost8083/8-Ball-Pool-Internal-Proxy-DLL-Source#5]
./libs/discord-rpc.lib;
./libs/cryptopp/lib/cryptopp-static.lib;
./libs/curl/lib/libcurl.lib;
./libs/openssl/lib/libcrypto.lib;
./libs/openssl/lib/libssl.lib;.
/libs/zlib.lib;
Normaliz.lib;

why you didn't add them to repo?

**Comment by localhost8083** [comment]
u can easily add them via vcpkg

**Comment by a-ahmed** [comment]
Yeah, thanks
